--CONCAT
SELECT
USERNAME_+' '+PASSWORD_+' '+NAMESURNAME AS NORMALYAZIM,
CONCAT(USERNAME_,' ',PASSWORD_,' ',NAMESURNAME) AS CONCATILE,
CONCAT_WS(' ',USERNAME_,PASSWORD_,NAMESURNAME) AS CONCATWSILE,
*
FROM USERS