SELECT 
	U.USERNAME_ KULLANICIADI,
	U.NAMESURNAME ADSOYAD,
	CT.CITY IL,
	T.TOWN ILCE,
	D.DISTRICT SEMT,
	A.ADDRESSTEXT ACIKADRES,
	O.ID SIPARISID,
	O.DATE_ TARIH,
	O.TOTALPRICE TUTAR,
	P.DATE_ ODEMETARIHI,
	P.APPROVECODE ONAYKODU,
	I.DATE_ FATURATARIHI,
	I.CARGOFICHENO KARGOFISNO,
	OD.*,
	IT.ITEMNAME URUNADI,
	IT.UNITPRICE URUNFIYATI

FROM ORDERS O 
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
WHERE O.ID=2613

