--ODEMETURUNE GORE
SELECT
DATEPART(YEAR,DATE_) AS YIL,
DATEPART(MONTH,DATE_) AS AY,
CASE
	WHEN PAYMENTTYPE=1 THEN 'KREDIKARTI'
	WHEN PAYMENTTYPE=2 THEN 'BANKAHAVALE'
END AS ODEMEYONTEMI,
SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS
GROUP BY DATEPART(YEAR,DATE_),DATEPART(MONTH,DATE_),PAYMENTTYPE
ORDER BY DATEPART(YEAR,DATE_),DATEPART(MONTH,DATE_)