SELECT
IT.CATEGORY1,IT.CATEGORY2,
SUM(OD.LINETOTAL) AS TOPLAMSIPARISTUTARI,
SUM(OD.AMOUNT) AS TOPLAMSIPARISADEDI,
COUNT(OD.ID) AS TOPLAMSIPARISADEDI,
SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS ORTALAMAADET

FROM ORDERS O 
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID

--WHERE CATEGORY1='EV'
GROUP BY IT.CATEGORY1,IT.CATEGORY2
ORDER BY SUM(OD.LINETOTAL) DESC