--FORMAT
SELECT FORMAT(GETDATE(),'D','EN-US') AS 'US ENGLIS RESULT',
	   FORMAT(GETDATE(),'D','EN-GB') AS 'GREAT BRITAIN ENG RESULT',
	   FORMAT(GETDATE(),'d','EN-US') AS 'US ENGLIS RESULT',
	   FORMAT(GETDATE(),'d','EN-GB') AS 'GREAT BRITAIN ENG RESULT'