SELECT CITY,
SUM(TOTALPRICE) AS TOTALPRICE_,
COUNT(DISTINCT CUSTOMERNAME) AS CUSTOMERCOUNT_
FROM SALES
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERNAME)>200
AND SUM(TOTALPRICE)>80000
ORDER BY SUM(TOTALPRICE)  DESC 