--LOWER,UPPER,REVERSE,REPLİCATE
SELECT 
	LOWER('MEHMET YILDIZ'),
	UPPER('mehmetyıldız'),
	REVERSE('MEHMET YILDIZ'),
	REPLICATE('XD',5)

SELECT * FROM TEST --TEST TABLE IN ETRADE4
UPDATE TEST SET SIRANO2=REPLICATE('0',8-LEN(SIRANO1))+CONVERT(VARCHAR,SIRANO1)