SELECT CITY,MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE_,
COUNT(DISTINCT CUSTOMERNAME) UNIQUECUSTOMER,
COUNT(DISTINCT FICHENO) AS CUSTOMERCOUNT_, 
COUNT(*) AS TOTALCOUNT_ 
FROM SALES

GROUP BY CITY,MONTHNAME_
ORDER BY CITY
