SELECT 
U.USERNAME_ KULLANICIADI,
U.NAMESURNAME ISIMSOYISIM,
U.EMAIL EPOSTA,
U.GENDER CINSIYET,
U.TELNR1 TELEFONNO,
C.COUNTRY ULKEADI,
CT.CITY SEHIRADI,
A.ADDRESSTEXT ACIKADRES

FROM USERS_ U,ADDRESS_ A,COUNTRIES_ C,CITIES_ CT
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
ORDER BY U.NAMESURNAME