--REPLACE
DECLARE @CUMLE AS VARCHAR(MAX)
SET @CUMLE='MERHABALR BEN MEHMET BEN IS YAPMAK BEN YEMEK YEMEYI COK SEVMEK BEN OLMAK 22 YASINDA BEN OLMAK OGRENCI'

SELECT REPLACE(@CUMLE,'BEN','HEHE')
--MERHABALR HEHE MEHMET HEHE IS YAPMAK HEHE YEMEK YEMEYI COK SEVMEK HEHE OLMAK 22 YASINDA HEHE OLMAK OGRENCI