--TRIM,LTRIM,RTRIM
SELECT TRIM(' MEHMET YILDIZ '), --'MEHMET YILDIZ'
	   LTRIM(' MEHMET YILDIZ '), --'MEHMET YILDIZ '
	   RTRIM(' MEHMET YILDIZ '), --' MEHMET YILDIZ'
	   LTRIM(RTRIM(' MEHMET YILDIZ ')) --'MEHMET YILDIZ'